name: CI

on:
  push:

jobs:
  test:
    name: Run test
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Get system locale
        run: Get-WinSystemLocale
        shell: powershell
      - name: Check python encoding on default locale
        run: |
          echo a | python -I -c "import sys; print(sys.stdin.encoding)"
          echo a | python -I -X utf8 -c "import sys; print(sys.stdin.encoding)"
      - name: Set system locale to JP
        run: Set-WinSystemLocale ja-JP
        shell: powershell
      - name: Check python encoding on JP locale
        run: |
          echo a | python -I -c "import sys; print(sys.stdin.encoding)"
          echo a | python -I -X utf8 -c "import sys; print(sys.stdin.encoding)"
