name: CI

on:
  push:

jobs:
  test:
    name: Run test
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set default locale to ja-JP
        run: Set-WinSystemLocale ja-JP
        shell: powershell
      - name: Check python encoding on default locale
        run: |
          python ci_encoding.py
